services:
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - "8080:8080"
    environment:
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME} 
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD} 
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_DATABASE_HOST: db
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - db
    restart: always

  db:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/bitnami/mariadb
    restart: always

volumes:
  wordpress_data:
  db_data:
